### ISSUE TITLE
Prepare repo for review and publishing

### ISSUE THREAD

**Issue by joseegm** [SAP/fundamental#1]
The following tasks are needed to be able to continue the publishing process.

### Tasks
- [x] Add 1.0 Beta code from Techne v2.0 Alpha
- [x] Add content to the README.md file - Structure is mandatory from https://jam4.sapjam.com/wiki/show/xPbngPlyfQkPnsfgNxWgx9
- [ ] ~~Add content to the CONTRIBUTING - based on~~ ~~https://github.com/SAP/openui5/blob/master/CONTRIBUTING.md~~
