### ISSUE TITLE
Test: Hover and Selected state for the elements in the Top Bar

### ISSUE THREAD

**Issue by joseegm** [SAP/fundamental#105]
### Goal
Test two variants for the hover and selected states on the Top Bar elements

### Current Visuals
https://app.zeplin.io/project/598cce4ab8aced8f15a420a1/screen/5a940e0faa10e027813e7ecb

### Tasks
* [ ] Create the variant with the inverted (white) background for the dropdown and the icons
* [ ] Create a test with both variants: The user should understand better what the dropdown is for with aid from the visual style
  * User task #1: Where to go to change applictions
  * User task #2: Change from Application A to Application B 
* [ ] Review the test results

**Comment by joseegm** [comment]
@LeoT7508 
You can start creating the visuals and we'll talk with Hanna next week.
