### ISSUE TITLE
[Test] QA in Firefox and IE browsers

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#114]
We have done no testing in non-Webkit browsers. There are def issues with some form elements due to lack of support for `:after` and `:before` pseudos for self-closing elements like `input`s.

There are potential markup changes required.

> NOTE: Additional issues may be opened based on this QA initiative.

## TODO: 
- [ ] Perform through QA for all compoents in Firefox 
- [ ] Perform through QA for all compoents in IE

## Issues found so far 

- [ ] Inner circle of radio not visible in firefox #778

**Comment by eboyer** [comment]
Closing to create additional tasks in the backlog.
