### ISSUE TITLE
[Lib] RTL Audit 

### ISSUE THREAD

**Issue by saad-mo** [SAP/fundamental#1177]
Test all components and identify which ones are lacking RTL support 

## The following components lack RTL support. 
- [ ] `action-bar` #1218 
- [ ] `select` #1219
- [ ] `calendar` #1220
- [ ] `form-group` this should be corrected with #1219
- [ ] `inline-help`#1221
- [ ] `list-group` #1222
- [ ] `menu` #1223
- [ ] `multi-input`this should be corrected once `menu` is fixed with #1223
- [ ] `modal` #1224
- [ ] `nav` #1225
- [ ] `pagination` #1226
- [ ] `panel` #1227
- [ ] `product-switcher` #1228
- [ ] `search-input` this should be corrected once `menu` is fixed with #1223
- [ ] `shellbar` #1229
- [ ] `sidenav` #1230
- [ ] `tile-grid` #1231
- [ ] `tree` #1232

-----

## The following components has RTL support. 
- `alert` 
- `badge` 
- `label` 
- `status-label`
- `button`
- `button-group`
- `breadcrumb`
- `checkbox`
- `contextual-menu`
- `combobox-input`
- `counter`
- `date-picker`
- `dropdown`
- `icon`
- `identifier`
- `image`
- `input`
- `input-group`
- `link`
- `localization-editor`
- `panel-grid`
- `popover`
- `product-menu`
- `product-tile`
- `radio`
- `spinner`
- `table`
- `tile`
- `time`
- `time-picker`
- `tabs`
- `token`
- `toggle`
- `user-menu`
