### ISSUE TITLE
Lib: Update shell footer

### ISSUE THREAD

**Issue by saad-mo** [SAP/fundamental#1293]
### Component name
> Update shell footer 

### Detailed description
> We already have markup for the footer in the shell, need to update it with the right sap logo.

### TODO: 
- [ ] update shell footer in components 
- [ ] add/update new documenation for shell 
- [ ] https://sap.github.io/fundamental/layouts/shell-layout.html

**Comment by pavan-sokke-nagaraj** [comment]
Can we have an option to remove the shell footer, if we do not want to use
