### ISSUE TITLE
Layouts documentation to the website

### ISSUE THREAD

**Issue by joseegm** [SAP/fundamental#137]
#### Goal
Add a site part to explain Application Level Structure Components and Layouts.

### Tasks
* [x] Decide how to call the vertical/part
  --> Layouts
* [x] Add the docs for the Application Level documentation - Application Layout
  * [x] Top bar + Content
  * [x] Top bar + Side bar + Content
* [x] Add the docs for the layouts components documentation - Content Layouts
  * [x] Vertical Sections
* [x] Add the docs for the grid
