### ISSUE TITLE
[WIP] v1.4.3 UI Kit Component Update Tracking List

### ISSUE THREAD

**Issue by saad-mo** [SAP/fundamental#1483]
This Issue is created to keep track of all the component updates following the release of UI KIT v1.4.3

### Grid
- [ ] Updated column, gutter, and margin specs.
- [ ] Addition of grid symbols to overlay for more accurate spacing.  

### Spacing
- [ ] Additional spacing guides for Home & Detail Pages. Includes margins and spacing between Panels. 

### Action Bar
- [ ] Addition of shadow below shape to add better visual separation from the content below. 

### Asset Upload [new component]
- [x] Additional component for potential drag & drop functionality, for now, a component is used for uploading any asset using the button. 
- [x] Upload File button for forms.

### Busy Indicator [update/new component]
- [x] Updated design. 
- [ ] Add loader on card

### Product Switcher
- [ ] New component design.

### Secondary Navigation 
- [ ] New component design

### Date Picker
- [ ] Fundamental Date Picker will differ from Global Design. 

### Left Navigation 
- [ ] Margins & Spacing updates.

### List Elements
- [ ] Addition of tiles with link titles.
- [ ] Addition of Tile with 3 lines. 

### Panels / Cards
- [ ] Left and right margins are 16px.
- [ ] Addition of panel/card with KPIs.
- [ ] Addition of Object variation. 
- [ ] Addition of Panel with counter.
- [ ] Panel Error state. 

### Tiles
- [ ] Updated margins to 16px.
- [ ] Addition of Link Title variations.  

### Shellbar
- [ ] Updated margins
- [ ] Button spacing is now 8px. 

### Page Types
- [ ] New component design.
- [ ] Addition of Page Types, Examples and Floorplans. These are prebuilt pages for designers to have a better starting point. 
- [ ] Addition of blank shell pages for designers to have a pre-built page structure to start with if they need a build a page from scratch. 
- [ ] Addition of grid guide overlays to help with layouts, these are included in each Page Type. 
- [ ] Italic text for placeholder text. 

### Typography
- [x] Additional type sizes added to type scale: 72px & 96px to account for KPIs. 
- [x] Addition of UI Control usages examples. 
- [x] Addition of Title Headlines Usage Example.
- [x] Addition of Display Texts Usage Example. 

### Colors #1491
- [x] Shell: Addition of Shell Hover, Shell Active, Shell Interactive. 
- [x] Background 1: Changed to f7f7f7.
- [x] Background 3-7: Addition of Background 3-7 colors.
- [ ] Neutral 2: Updated to #EDEDED
- [x] Addition of Neutral 5 & 6. 
- [x] Removal of State colors: Positive, Alert, Negative. (Moved to Background section)
- [x] Updated Accent colors: 1,2,6,7,10. 

### Alerts / Message Strips #1492
- [x] Add text only variation.
- [x] Add wrapping text variation.

### Identifier / Avatar #1494
- [x] Update scales (replace 36 with 32, add 64, 80 and 112)

### Breadcrumb
- [x] Updated design & spacing.

### Forms #1498
- [x] Updated Disabled state.
- [x] Additional support for error, warning, success, Information states of fields
- [x] Italic text for placeholder text.  
- [ ] Upload File button for forms. - this is a new component

### Radio Button #1497
- [X] Sizing of shapes updated. 

### Check Box 
- [x] Updated selected state.

### Links 
- [x] Added variations of Icon and emphasized variation for the link

### Search 
- [x] Italic text for placeholder text.

### Status Indicators
- [x] Grey version removed. 
- [x] Updated color variations. 
- [x] Updated text colors.

### Table #1500
- [x] Make column headers Camel Case.
- [x] Update column header idle grey color to Neutral 5.
- [X] New symbols for row status’ (Positive, Warning, Negative). 

### Toggle [done]
- [x] Changed size from 28 to 32px.
- [x] Add additional colors.
- [x] Add additional states.
- [x] Add additional status’.  

### Token [done]
- [x] Update colors for token shape
- [x] Addition of documentation for application inside fields. Token

### Modal
- [x] Change name to dialog or (modal/dialog)
