### ISSUE TITLE
Improve Layout documentation

### ISSUE THREAD

**Issue by joseegm** [SAP/fundamental#152]
### Goal 
Include missing helpers and elements on the documentation.

### Tasks
- [x] Add documentation for the header modifiers.
- [x] Add documentation for the Overlays elements
  - [x] Add Overlays elements to the main structure documentation
  - [x] Add an example with the overlay shown
