### ISSUE TITLE
Visual Alignment Panels

### ISSUE THREAD

**Issue by joseegm** [SAP/fundamental#162]
### Goal
Visual alignment for the panel component with the MD Cards.

### Current
https://sap.github.io/fundamental/components/panel.html

### Reference
https://app.zeplin.io/project/5a5e1cb96e836180d25dfebd/screen/5a8b14946715ae8dad9520ca

<img width="756" alt="screen shot 2018-04-03 at 11 09 42" src="https://user-images.githubusercontent.com/22662903/38240301-8d679ffc-372f-11e8-94a8-9051518dc131.png">

**The Fundamental Panel Component will serve as the Modular Design Card Component** due to the similarities of the MD Card components with it.

### Tasks
- [ ] Adjust the Background colors and visual elements of the Panel elements: Header, Content and Footer
- [ ] Change the typography of the Panel title accordingly 
- [ ] Change the spacing and size of the actions
