### ISSUE TITLE
Move Techne v2.0 Code 

### ISSUE THREAD

**Issue by joseegm** [SAP/fundamental#2]
### Tasks
- [x] Copy code Verbatim
- [x] Clean old and unused files
- [x] Update readme and some documentation files
