### ISSUE TITLE
Docs: Site updates tracking list 

### ISSUE THREAD

**Issue by saadmhybris** [SAP/fundamental#262]
**Fundamentals**
- [x] Getting Started - Designers
- [x] Getting Started - Developers #287
- [x] Colors  - colors updated, will need new layout design  #183 
- [x] Grid  - need design direction #186 
- [x] Spacing - need design direction #185 
- [x] Type - need design direction #184 

**Components**
- [x] .fd-action-bar #263
- [x] .fd-alert #266
- [x] .fd-badge | .fd-label - #273
- [x] .fd-button #268
- [x] .fd-button-group #277
- [x] .fd-breadcrumb #180
- [x] .fd-card, .fd-card-group, .fd-toolbar - depricated, remove from site #270
- [x] .fd-contextual-menu #282 
- [x] .fd-dropdown #327
- [x] .fd-form > .fd-form__group #276 
- [x] .fd-global-nav #181 
- [x] .fd-icon #289 
- [x] .fd-identifier #278 
- [x] .fd-image #291 
- [x] .fd-inline-help #293
- [x] .fd-input-group #279 
- [x] .fd-link #295
- [x] .fd-list-group #303
- [x] .fd-mega-menu #305
- [x] .fd-modal #217 #274(pr) 
- [x] .fd-pagination #331
- [x] .fd-spinner #317
- [x] .fd-side-nav #182 
- [x] .fd-table #316
- [x] .fd-tabs #315
- [x] .fd-toggle #314
- [x] .fd-tree #333
- [x] .fd-tag #313
- [x] .fd-tile, .fd-product-tile, .fd-tile-grid #335

**Layout #347**
- [x] .fd-ui .fd-app
- [x] .fd-ui__overlay
- [x] .fd-page
- [x] .fd-section
- [x] .fd-panel
- [ ] .fd-container .fd-col

**App Template Pages**
- [x]  - Full-width
- [ ]  - Sidebar

**Content Pages**
- [x]  - ~~Cards~~
- [x]  - Tile
- [x]  - Table
- [x]  - Tree
- [x]  - Empty Page
- [x]  - ~~Details 1~~
- [x]  - ~~Details 2~~

**Comment by saadmhybris** [comment]
@jeannewalters I created this issue to check of components that are updated with the markup and documentation.
