### ISSUE TITLE
Top and Side Navigation

### ISSUE THREAD

**Issue by joseegm** [SAP/fundamental#29]
### Description
The Top and Side navigation will support intra and inter navigation on Fundamental UI Applications.

> **Intra app navigation:** navigation inside a single, standalone application. **Inter app navigation**: navigation to other, related standalone applications.

### Features

1. **Top navigation**:
  1.1 Can be used standalone without the side navigation
  1.2 Support for application branding, logo and name
  1.3 Support for Inter application navigation
  1.4 Support for Intra application navigation: access main application areas
  1.4.1 Should clearly display the current application area
  1.5 Support for application global actions: help, profile, settings, configuration, etc.
  1.6 Support for application wide search.
  1.7 Support a way to show/collapse the side navigation

2. **Side navigation**:
  2.1 ~Can be used standalone without the Top navigation~
  2.2 ~Support for application branding, logo and name~
  2.3 Support for Intra application navigation: access main application areas
    2.3.1 Support for deeper Intra application navigation: collapsible options, etc.
    2.3.2 Should clearly display the current navigation node
  2.4 ~Support for application global search~
  2.5 ~Support for global actions: help, profile, settings, configuration, legal information, etc.~

3. The Top and Side navigation can be use independently depending on the type of application.

### Tasks
- [x] Investigate the current UIs.
- [x] Wireframes for features on the Top Navigation
- [x] Wireframes for features on the Side Navigation
- [x] Review Wireframes
- [x] Visuals for the Top Navigation
- [x] Visuals for the Side Navigation
- [ ] Review Visuals

### Wires
https://5dh5bc.axshare.com/#g=1&p=launchpad_header

### Visuals
https://app.zeplin.io/project/598cce4ab8aced8f15a420a1/screen/5a940e0faa10e027813e7ecb

**Comment by jeannewalters** [comment]
The following wiki page is a review of what I went over in our call today:
https://wiki.hybris.com/pages/viewpage.action?pageId=365546661

Wires are here:
https://5dh5bc.axshare.com/#g=1&p=launchpad_header

**Comment by jeannewalters** [comment]
Assigning it to @joseegm for review.

**Comment by joseegm** [comment]
After reviewing the wires, almost all the features are designed, still some are missing:

1.  **Top navigation**:
  * **1.4** and **1.4.1**. Intra app navigation: The same way service factory does
  * **1.6**. Missing. Should this be an icon or a search input on the top bar
2. **Side navigation**:
  * **2.2**. Missing.
  * **2.4**. Missing.
  * **2.5**. Missing.

**Comment by joseegm** [comment]
Updated to strike out the features not needed on the side nav

**Comment by joseegm** [comment]
@LeoT7508 
Can you update this with the Zeplin link?

**Comment by LeoT7508** [comment]
@joseegm 

This will be posted next week when @jinjiahuangsap  is back and  can put the finishing touches on the work he's been doing.

**Comment by joseegm** [comment]
@LeoT7508 @jinjiahuangsap 
The changes are already on Zeplin.

**Comment by joseegm** [comment]
@LeoT7508 
Yes, make sure we are using the same spacing like the other components, I think we didn't take that much in count with these visuals. Also it needs to be denoted as well. Just realised that looking at the sizes.

**Comment by LeoT7508** [comment]
@joseegm 

The spacing is correct as far as I know. @jinjiahuangsap lets double check this.

**Comment by LeoT7508** [comment]
@joseegm @jeannewalters @xak 

The Zeplin design sheet is updated. 

https://zpl.io/VQWRLd5
