### ISSUE TITLE
Migration Changes to the Library

### ISSUE THREAD

**Issue by joseegm** [SAP/fundamental#3]
### Tasks

- [x] Test the library code dev environment is running
- [x] Change namespaces and other old Techne related identifiers
- [x] Test building process
