### ISSUE TITLE
Component Taxonomy match with Fiori

### ISSUE THREAD

**Issue by joseegm** [SAP/fundamental#30]
### Description
The Fundamental UI Components should have the same name as their Fiori counterpart

### First matching
https://wiki.hybris.com/display/yintfdes/Comparison+of+Fundamental+and+Fiore+Components

### Tasks
 - [x] Fundamental Components comparison against Fiori Components
 - [x] Define the nomenclature and Taxonomy changes
 - [ ] ~Identify missing components in Fundamental UI.~

**Comment by joseegm** [comment]
> Moved from Techne issue

@jeannewalters 
I have reviewed the results of the investigation and there is some improvements that can be made:
1. "All of what is labeled as a Button in Fundamental UI is part of "Action" submenu in Fiore." - This statement is not so clear, we have different types of Buttons, The Dropdown Menu Fundamental have is a different component.
2. The screenshot of the "Lists" under "Cards" is not really Cards that's a normal table where you can select/check the rows. See the example: http://sap.github.io/techne/table.html#table-with-checkbox
3. The Dropdown component is not exactly the same as the ComboBox in fiori. That is still to be decided if a component like that will be part of the Fundamental UI Dropdown or a new component with that functionality.

All others are fine, the similarity is there.

**Comment by joseegm** [comment]
@jeannewalters 
Let me know if this is finished and feel free to close it. I'll then move it on to development for assessing the changes.

**Comment by jeannewalters** [comment]
I'll take a look at it in a few min.

**Comment by jeannewalters** [comment]
1) **Your questions -** "All of what is labeled as a Button in Fundamental UI is part of "Action" submenu in Fiore." - This statement is not so clear, we have different types of Buttons, The Dropdown Menu Fundamental have is a different component.   
**My response:**
The actions in Fiore are a combination of what you have as buttons in Fundamental. Take a look at their way of breaking "Actions" down - You will have to expand the left menu to see this as there is no landing page for Actions: 
https://experience.sap.com/fiori-design-web/button/
https://experience.sap.com/fiori-design-web/link/
https://experience.sap.com/fiori-design-web/menu-button/
https://experience.sap.com/fiori-design-web/smart-link/
![image](https://user-images.githubusercontent.com/24274321/35974791-d5f129ae-0cb0-11e8-866d-b727333e80cf.png)

2) **Your question** The screenshot of the "Lists" under "Cards" is not really Cards that's a normal table where you can select/check the rows. See the example: http://sap.github.io/techne/table.html#table-with-checkbox
**My response**
I agree that the first example in that column is a table. I've removed it.
The next version of Fiore is highly focused on cards:
![image](https://user-images.githubusercontent.com/24274321/35975125-fdb7f4b2-0cb1-11e8-9dbb-67b90d231570.png)


3)  **Your question**The Dropdown component is not exactly the same as the ComboBox in fiori. That is still to be decided if a component like that will be part of the Fundamental UI Dropdown or a new component with that functionality.
**My response** . I think they separate out the dropdown box more discreetly so we can either do that or leave it as dropdown.

**Comment by joseegm** [comment]
1. Yes, naming it actions will make also more sense now. We also almost the same types
2. Good.
3. Yes, we still are missing other components that look like the dropdown but is something else.
