### ISSUE TITLE
Migration changes to the Website

### ISSUE THREAD

**Issue by joseegm** [SAP/fundamental#4]
### Tasks

- [x] Change references to the new build of Fundamental, not referencing to Techne CSS/SCSS files
- [x] Change all namespaces on the CSS classes on the website
- [x] Change all website references to Techne in build process, files, folders etc.
- [x] Test the website build process
- [x] Visual check - @Jose
