### ISSUE TITLE
Publish NPM package

### ISSUE THREAD

**Issue by joseegm** [SAP/fundamental#5]
### Tasks

- [x] Check the library building process is working properly
- [x] Check dist paths and filenames are correct to Fundamental -not Techne
- [x] Change package.json to Fundamental v1.0-beta; also description license and others.
- [x] Create new package on npm.org
- [x] Connect npm to github and other configuration needed
- [x] Release Fundamental v1.0-beta on github / push new version to npm
- [x] Check the new package is working / downloading properly - @saadmhybris, @xak, @ joseegm
