### ISSUE TITLE
Release: V1.1.0 Release notes

### ISSUE THREAD

**Issue by saadmhybris** [SAP/fundamental#523]
Check off items below as documentation is added/updated. 

### New 
- [x]  Time / Time Picker #453
- [x]  Calander / Date Picker #548
- [x] Menu / Popover #455
- [x] Status Label #462

### Upated 
- [x] Action Bar - responsive support added  #529
- [x] Alert - minor design changes, document palcement on a demo page  #472  
- [x] Button updates - down and hover state added  #530 
- [x] Badge & Label - minor design changes. **no docs update needed, verify css update** 
- [x] Modal - minor design changes, change button from action bar to primary. #531
- [x] Number input group, minor design changes. **no docs update needed, verity css update**
- [x] Input Field and dropdown, minor design changes.    markup updated with change in icon
- [x] Panel (added support for description field)
