### ISSUE TITLE
Visual Experiments for the Fiori Aproximation 

### ISSUE THREAD

**Issue by joseegm** [SAP/fundamental#59]
### Description
Experiment how the Current version of the library will looks like if we approximate it to Fiori.

### Tasks
- [x] Change only the global color palette using Belize colors
  --> Result:  https://app.zeplin.io/project/5a5faea7d41af9a6b277e603
- [ ] Visual Experiment in Fiori Direction
- [ ] Visual Experiment in PIM Style Direction

**Comment by joseegm** [comment]
@LeoT7508 
Remember to always update, move and close the tickets you are working on.
