### ISSUE TITLE
v1.2.0 Release Notes 

### ISSUE THREAD

**Issue by saadmhybris** [SAP/fundamental#590]
### New Component 
- [x] Multi-Input #660
- [x] Combo-Box #661
- [x] Search-Box #662
- [x] Multi-Tab Editor #663

### Component Improvements 
- [x] Table - sortable column and fixed column styling - #664
- [x] Menu - added support for `<hr>`, addon item before  #665

### Bugs Fixes & Improvements 
- [x] Removed NPM as a direct dependency. Using it as engine instead. 
- [x] Fixed critical and some high sevierity security vurnabilities with non-breaking changes 
- [x] Forms - Color and hover states updates 
- [x] Toggle - Color, active and disabled states udpates 
- [x] Contextual Menu with issues 
- [x] Responsive layout improvements - Reduced extream padding on smaller screens 
- [x] Backgroun color toggle on component display 
- [x] Color Palette Update & Addition - `status-1`, `status-2` colors updated, `neutral-4` added
- [x] Page container height fix - no more unnecessary scroll bars
