### ISSUE TITLE
Dashboard Components

### ISSUE THREAD

**Issue by joseegm** [SAP/fundamental#62]
### Description
Research and Design a set of components or changes to current components to allow constructing Dashboard screens with Fundamental Components.

### Features
- **1**. The dashboard screen should support showing different metrics
- **2**. The dashboard elements that contain the metrics should support different sizes
- **3**. The dashboard elements that contain the metrics should be able to show and perform actions that change the element or the way the information is displayed inside
  - **3.1** The dashboard elements can be used as a navigation point
    - **3.1.1** The dashboard elements used as a navigation points should have a different visual style
- **4**. The dashboard screen can also support other Fundamental UI Components

### Tasks
- [ ] Find a suitable name for the Dashboard elements that works with the Fundamental UI names currently in use; also a name for the different parts of the Dashboard element
- [ ] Identify the types of Dashboard elements: single metric, chart, actions, etc
- [ ] Research if the current Fundamental UI Card component can support the identified types of Dashboard elements
- [ ] Design the common layout of the Dashboard element to support all features
- [ ] Design the interaction inside the Dashboard element: actions, charts, etc.

### Deliverables
- [ ] Dashboard element name and the parts names as well
- [ ] Table with description of different types of Dashboard elements indentified
- [ ] Wireframes describing the different types of Dashboard elements
  - [ ] Wireframes describing the different types of Dashboard elements parts
  - [ ] Wireframes describing the Interactions of the Dashboard elements
- [ ] Wireframes of a sample full Dashboard screen that showcase all the types of Dashboard elements and their interaction
