### ISSUE TITLE
Website Font Style bleeding inside the components

### ISSUE THREAD

**Issue by joseegm** [SAP/fundamental#70]
### Problem
The Styles of the Website are cascading and bleeding inside the components.

For example the cards
<img width="1291" alt="screen shot 2018-02-12 at 14 24 15" src="https://user-images.githubusercontent.com/22662903/36098785-8ad1d8ee-1000-11e8-9aa8-1afa6179c9c6.png">

This only happen on the website, the kitchen sink app have the correct font
<img width="1457" alt="screen shot 2018-02-12 at 14 24 39" src="https://user-images.githubusercontent.com/22662903/36098803-9d9536e2-1000-11e8-901c-02ac569d45c4.png">

### Tasks
- [x] Check all components on the website where this problem might be happening - Leo, Jinjia
- [x] Change the affected components

### Results
- [x] List of all affected components
- [x] Changes to the components in the library code

**Comment by jinjiahuangsap** [comment]
Would you mind sharing the tool you are using for checking the style? It looks super cool in the screenshot:) @joseegm

**Comment by joseegm** [comment]
@jinjiahuangsap Sure: http://www.chengyinliu.com/whatfont.html
