### ISSUE TITLE
Update accent colors

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#733]
## Update accent color palette to combine the two groups. The 3:1 colors should be 1-10, the 4.5:1 colors should be 11-16.

The value is to logically group the colors by use. Only the 4.5:1 colors can be used with text, e.g., for identifiers, since they pass accessibility, therefore it should be easy for a dev to access those colors. 

## Use case
- New user signs up with no photo so the system must assign a color to the identifier.
<img width="58" alt="screen shot 2018-10-16 at 5 43 19 am" src="https://user-images.githubusercontent.com/424119/47011060-7f446d80-d106-11e8-979c-f1fefc1ea624.png">

- The system randomly picks a number between 11-16 to assign an accessible color.

This can also be more easily documented so designers learn the differences in the accent color palette and when to use which color.

#### References
Design sheets available here:
https://app.zeplin.io/project/5b169f030f5e5e5d1255fe46/screen/5bbe4ba53368160a32fc1329

[F3_Colors_Preview_v1_Oct4.pdf](https://github.com/SAP/fundamental/files/2458416/F3_Colors_Preview_v1_Oct4.pdf)
[F3_Colors_v1_Oct4.pdf](https://github.com/SAP/fundamental/files/2458417/F3_Colors_v1_Oct4.pdf)

## Updates

- [x] Add/update accent colors in the `settings` color map
  - [x] Accent 1: Update #e38b16
  - [x] Accent 2: Update #ee6868
  - [x] Accent 3: Update #ed4a7b
  - [x] Accent 4: Update #c0399f
  - [x] Accent 5: Update #686cdf
  - [x] Accent 6: Update #5899da
  - [x] Accent 7: Update #13a4b4
  - [x] Accent 8: Update #7ca10c
  - [x] Accent 9: Update #955ecf
  - [x] Accent 10: Update #6C8893
  - [x] Accent 11: Add new color #2b78c5
  - [x] Accent 12: Add new color #6367de
  - [x] Accent 13: Add new color #984bd2
  - [x] Accent 14: Add new color #c0399f
  - [x] Accent 15: Add new color #db1f77
  - [x] Accent 16: Add new color #66768a

> HSL values are included in the design specs

- [x] Add new accents to `core/_root`

- [x] Update test styles page — http://localhost:3030/pages/styles

- [x] Update the docs page — https://sap.github.io/fundamental/foundation/colors.html

- [x] Update the helpers page — https://sap.github.io/fundamental/guides/design-system-utilities.html

**Comment by LeoT7508** [comment]
@xak 

We have 6 4.5.1 to accommodate type on top of those colors, and 10 3.1 colors that do not.
