### ISSUE TITLE
Update core color palette

### ISSUE THREAD

**Issue by LeoT7508** [SAP/fundamental#739]
Verify core colors are correct.

**Action**
- [x] Action 1: Update #0a6ed1
- [x] Action 2: Add new color #ffffff

**Shell**
- [x] Shell 1: Add new color #354a5f
- [x] Shell 2: Add new color #d1e8ff

**Text**
- [x] Text 3: Update #6a6d70
- [x] Text 4: Update #74777a
- [x] Text 5: Update #ffffff

**Background**
- [x] Background 1: Update #edeff0

**Neutral**
- [x] Neutral 4: Update #8b949c

**Status**
- [x] Status 1: Update ##107f3e
- [x] Status 3: Update #e00000
- [x] Status 4: Add new color #687173

Design sheet available here:
https://app.zeplin.io/project/5b169f030f5e5e5d1255fe46/screen/5bbe4ba53368160a32fc1329

## Updates

- [x] Update all `text(4)` instances to `text(5)`

- [x] Update docs example page
