### ISSUE TITLE
Update Color Palette to Fiori 3 - pt: 2

### ISSUE THREAD

**Issue by LeoT7508** [SAP/fundamental#740]
Update Accent Colors:

Names for these colors are up for conversation. 

**Chart Colors**

- [ ] Chart 1: Update #e38b16
- [ ] Chart 2: Update #ee6868
- [ ] Chart 3: Update #ed4a7b
- [ ] Chart 4: Update #c0399f
- [ ] Chart 5: Update #686cdf
- [ ] Chart 6: Update #5899da
- [ ] Chart 7: Update #13a4b4
- [ ] Chart 8: Update #7ca10c
- [ ] Chart 9: Update #955ecf

**Accent Avatar/Identifier**

- [ ] Identifier 1: Add new color #2b78c5
- [ ] Identifier 2: Add new color #6367de
- [ ] Identifier 3: Add new color #984bd2
- [ ] Identifier 4: Add new color #c0399f
- [ ] Identifier 5: Add new color #db1f77
- [ ] Identifier 6: Add new color #66768a

Design sheets available here:
https://app.zeplin.io/project/5b169f030f5e5e5d1255fe46/screen/5bbe4ba53368160a32fc1329
