### ISSUE TITLE
Lib: Color Palette Updates

### ISSUE THREAD

**Issue by LeoT7508** [SAP/fundamental#881]
## Tasks

- [ ] Update all colors in settings `fd-colors` map 
- [ ] Update test styles page — http://localhost:3030/pages/styles
- [ ] Update docs colors page — http://localhost:4000/foundation/colors.html

Design sheet can be found here:  https://zpl.io/2yl9EeJ

----

## Affected colors

**Shell**
Update Shell 2:
- [x]  Updated color is #D1E8FF

**Neutrals**
Update Neutral 3
- [x]  Updated color is #D9D9D9

Update Neutral 4
- [x]  Updated color is #89919A

**Status**
Update Status 3
- [x]  Updated color is #BB0000

Update Status 4
- [x]  Updated color is #6D7678

**Accent**
Update Accent 2
- [x]  Updated color is #DC7474

Update Accent 3
- [x]  Updated color is #DB1F77

Update Accents 5
- [x]  Updated color is #6367DE

Update Accent 11
- [x]  Updated color is #d17f15

Update Accent 12
- [x]  Updated color is #d04343

Update Accents 13
- [x]  Updated color is #2b78c5

Update Accent 14
- [x]  Updated color is #0f828f

Update Accents 15
- [x]  Updated color is #647887

Update Accent 16
- [x]  Remove color

**Comment by xak** [comment]
@LeoT7508 Please combine this with #848 and #882. These changes can be done all together.
