### ISSUE TITLE
UX: Translation Editor and Multi Tab Panel

### ISSUE THREAD

**Issue by joseegm** [SAP/fundamental#94]
**Description**
- Revise the locatlization to offer a solution where it doesn't affect the layout.
- Add the Multitab editor to Fundamental and clarify it can only be used within a panel

### Prior art
https://techne.yaas.io/patterns/Multi-Tab-Editor.html

### Tasks
* [ ] Check if all documented uses cases still valid
* [ ] ~Check the current approach to display many tabs. Now is under a dropdown menu, it will be better to have it all scrolling horizontally~
* [ ] Update the visual style to match the Fundamental Visual Style 

Support the following approaches:
1) Locale button inside field
2) Tabs for panels
3) Globe switcher in header that includes translations and application default language

Wires:
![long_text](https://user-images.githubusercontent.com/24274321/41421918-d5b694a6-6fc5-11e8-99c4-7d70e9fb7de4.png)
![dropdown](https://user-images.githubusercontent.com/24274321/41421919-d5ceb8e2-6fc5-11e8-9b40-cfd87d21b0e3.png)
![text](https://user-images.githubusercontent.com/24274321/41421920-d5e35856-6fc5-11e8-9e63-894564b6d92a.png)
![tabs](https://user-images.githubusercontent.com/24274321/41421921-d5f9f8fe-6fc5-11e8-991b-8876bf89a56d.png)
![locale_switcher_in_page_starter](https://user-images.githubusercontent.com/24274321/41421935-daf85ed6-6fc5-11e8-9170-f2882e338053.png)

**Comment by gcho1023** [comment]
the second error of the tabs should be called "Error state for Active Tab"

**Comment by gcho1023** [comment]
How would the user know they need to click on EN to see multiple languages available? Right now it doesnt indicate many languages...What would the error states look like if for example DE is required and user forgets to enter it?

**Comment by jeannewalters** [comment]
Here are the error states if the field or localized lang is required:
![image](https://user-images.githubusercontent.com/24274321/39587294-2766ba26-4ec7-11e8-8a60-fa90fad8b50d.png)

**Comment by gcho1023** [comment]
just adding on more thinking: is it possible to include a number of error next to the '!' ? doing heuristic evaluation, doesnt really diagnose how many errors users need to solve? would this work with larger heigh text fields?

**Comment by jeannewalters** [comment]
![image](https://user-images.githubusercontent.com/24274321/40511497-e6e12e98-5f6d-11e8-9040-ff6d041cc35d.png)

**Comment by LeoT7508** [comment]
@jeannewalters 

For the localized page the placement of that wont work. Thats where the page level buttons go. Why wouldn't we put this in the global nav?

**Comment by jeannewalters** [comment]
@xak @LeoT7508 Take a look at the updated field level wires. @LeoT7508 For the page level switcher, I just tried to cover the use case shown on the current techne lib - see bottom of page https://techne.yaas.io/patterns/Multi-Tab-Editor.html - I didn't put together the original concept, just trying to cover it. It makes sense to put it up at App level.

**Comment by xak** [comment]
I'm not certain the `!` and `2` indicators are necessary. It's a little extra overhead that the error handler needs to know the count of the errors. The form containers are dumb, they just know there is an error but nothing about the error. The message itself would be a better place to include that info, e.g., `(!) 2 required fields have no value`

Also, the way the label become part of the component will require a special approach. It would better if we could disconnect the `input` element from the label. Could the default state be like a `date-picker` with maybe a `globe` icon, clicking it opens the menu with all inputs exposed. The value could still be the default `EN` value. Do we need an `X` since we don't include that on other menus? It would close when you click off of it.

Although, I'm not entirely clear if the default value is editable without opening the menu. Would I ever see the `DE` or `ZH` values when the menu is closed? 

<img width="320" alt="screen shot 2018-06-01 at 11 30 37 am" src="https://user-images.githubusercontent.com/424119/40863740-8c61ccda-65b6-11e8-9375-2910d88bea91.png">

**Comment by jeannewalters** [comment]
@saadmhybris Can you pls take a look at the wires and annotations? Pls let me know if you have any questions. @LeoT7508 I am moving this to the visual column.

**Comment by saadmhybris** [comment]
<img width="261" alt="screen shot 2018-06-18 at 11 11 25 am" src="https://user-images.githubusercontent.com/15215400/41548785-880b3212-72e9-11e8-83cd-ef0a1df4e41a.png">



Do we need to add the error triangle within or adjacent to the error input field as well? going back to my concern about someone not being able to color, is it enough to have the error triangle in the error summary below the base field? we go have a reference to the field there (SP, PL), but I feel it's still not enough for quick scanning.

**Comment by saadmhybris** [comment]
@LeoT7508 

you can move forward with the design. I will raise this issue again during the development phase.

**Comment by LeoT7508** [comment]
@xak @saadmhybris @Jagoooo @jeannewalters 

Updated design sheet here:

https://app.zeplin.io/project/5b23c972a7bb309e08b88e95/dashboard?seid=5b2aaf2874f5a68f1a39c2cf
